apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-pod-configmap
data:
  application.yaml: |+
    server:
      port: 8080
    ---
    database:
      url: 10.5.0.xxxx
      username: ${DB_USERNAME:default}
      password: ${DB_PASSWORD:default}