spring:
  cloud:
    stream:
      binders:
        # broker one
        kafka-broker-0:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: localhost:9092
            # zkNodes: localhost:2181 deprecated since 2.0
            autoAddPartitions: true
            autoCreateTopics: true
        # broker two
        kafka-broker-1:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: localhost:9093
            # zkNodes: localhost:2182 deprecated since 2.0
            autoAddPartitions: true
            autoCreateTopics: true
      bindings:
        customerConsumer0:
          binder: kafka-broker-0
          group: Customer.Group
          destination: topic.customer.0
        customerProducer0:
          binder: kafka-broker-0
          destination: topic.customer.0
          producer:
            configuration:
        customerConsumer1:
          binder: kafka-broker-1
          group: Customer.Group
          destination: topic.customer.1
        customerProducer1:
          binder: kafka-broker-1
          destination: topic.customer.1
          producer:
            configuration: