web-client:
  base-url: http://0.0.0.0:6060
  headers:
    x-key: "CDERF"
    X-code: "5505"
  all-product-uri: /product/all
  all-product-url: ${base-url}/product/all
  get-product-uri: /product/{id}
  get-product-url: ${base-url}/product/{id}
  create-product-uri: /product
  create-product-url: ${base-url}/product
  update-product-uri: /product/{id}
  update-product-url: ${base-url}/product/{id}


