apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-pvc-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pvc-pod
  template:
    metadata:
      labels:
        app: spring-pvc-pod
    spec:
      containers:
        - name: spring-pvc-container
          image: tirmizee/spring-pvc:0.0.1
          volumeMounts:
            - name: pvc-volume
              mountPath: /data
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: host-pvc