sftp:
  client:
    host: 0.0.0.0
    port: 2222
    username: user
    password: pass
    time-out: 10000
    allow-unknow-key: true
    shared-session: true
    cache:
      pool-size: 5
      test-session: true
      session-wait-timeout: 30000
  inbound:
    remoteDirectory: /remote
    remoteFilesFilter: "*.txt"
    remoteFilesDelete: true
    localDirectory: /Users/pratya.yeekhaday/Desktop/local
    localDirectoryAutoCreate: true
logging:
  level:
    org.springframework.integration.sftp: TRACE
    com.jcraft.jsch: DEBUG


