apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pod
  template:
    metadata:
      labels:
        app: spring-pod
    spec:
      containers:
        - name: spring-pod
          image: tirmizee/spirng-configmap-env:0.0.2
          ports:
            - containerPort: 8080
          envFrom:
            # get configmap all key
            - configMapRef:
                name: spring-pod-comfigmap
          env:
            # get configmap by key
            - name: EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: spring-pod-comfigmap2
                  key: expire
