version: '3'
services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=posttgresuser
      - POSTGRES_PASSWORD=posttgrespassword
      - POSTGRES_DB=rainbow
