apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-secret-pod
spec:
  selector:
    matchLabels:
      app: spring-secret-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-secret-pod
    spec:
      containers:
        - name: spring-secre-container
          image: tirmizee/spring-secret:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
