apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  url: MTkyLjE2OC4wLjEx
  username: cm9vdA==
  password: emFxMTJ3c3g=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret2
type: Opaque
data:
  token: emFxMTJ3c3g=